### ISSUE TITLE
Completion block of scoutImageWithURI() never gets called

### ISSUE THREAD

**Issue by ashishkk** [kaishin/ImageScout#13] opened 2015-10-19 23:00 UTC
I tried to print the image size of a valid URI. But the completion block never gets called. What might be the issue?

**Comment by kaishin** [comment] 2015-10-20 08:58
Can you check if this addition to the README could help? https://github.com/kaishin/ImageScout/pull/12/files

**Comment by ashishkk** [comment] 2015-10-20 09:33
I am keeping a reference to the ImageScout instance like in the usage section in README but the completion handler is not executing.

**Comment by kaishin** [comment] 2015-10-20 11:38
@ashishkk Can you try with other images to make sure the issue is not coming from the image?

**Comment by ashishkk** [comment] 2015-10-20 11:47
@kaishin I just tried the Google logo from https://www.google.com.np/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

It's not calling the completion handler. Any idea what might be the issue?

**Comment by ashishkk** [comment] 2015-10-20 12:01
@kaishin I figured out the issue. [unowned self] is causing the issue when assigning the closure to operation.completionBlock inside the implementation of scoutImageWithURI(URI: String, completion: ScoutCompletionBlock).

When I removed that [unowned self] statement, only then it calls the completion block.

**Comment by kaishin** [comment] 2015-10-20 12:27
@ashishkk No that is not the issue. Removing the unowned reference causes a leak because the completion block and the scout instance strongly reference each other.

If removing that solves the problem for you it means that your scout instance is being released before the completion block fires.

Can you paste the code where you call `scoutImageWithURI`? Also how and where you init the scout instance?

Please look at the demo app (just updated to work with latest Xcode) and see how it should be done. I just tried with the same image and it worked.

**Comment by ashishkk** [comment] 2015-10-20 12:33
@kaishin Here is the snippet of the code.

override func viewDidLoad() {
        super.viewDidLoad()        
        let scout = ImageScout()
        
        scout.scoutImageWithURI("https://www.google.com.np/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png") { error, size, type in
            if let unwrappedError = error {
                print(unwrappedError.code)
            } else {
                print("Size: \(size)")
                print("Type: \(type.rawValue)")
            }
        }
    }

**Comment by kaishin** [comment] 2015-10-20 12:40
@ashishkk Yes, you need to move `let scout = ImageScout()` outside of the `viewDidLoad` otherwise it gets released as soon as the view is done loading.

**Comment by ashishkk** [comment] 2015-10-20 12:42
@kaishin Yeah. You're right. Just figured it out. Thanks.

**Closed** 2015-10-20 12:45 UTC
